# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "users", :force => true do |t|
    t.column "username", :string
    t.column "password", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "email", :string
    t.column "password_hint", :string
    t.column "assigned", :string
    t.column "family", :string
  end

  create_table "wants", :force => true do |t|
    t.column "user_id", :integer
    t.column "gottahave", :string
    t.column "position", :integer
    t.column "created_on", :datetime
  end

end
